### PR TITLE
fixed coverage error

### PR DESCRIPTION
**Pull request by calum-gray**
says 0% for some reason but on phpstorm it shows properly

### CODE REVIEW

**Review by Tahmid11 — COMMENTED** [review]
Why did you remove the requireCoverageMetadata? 

Can you explain the change made to line 41 in phpunit.xml?

**Comment by calum-gray** [comment]
> Why did you remove the requireCoverageMetadata?
> 
> Can you explain the change made to line 41 in phpunit.xml?

made it work

**Comment by Tahmid11** [comment]
> > Why did you remove the requireCoverageMetadata?
> > Can you explain the change made to line 41 in phpunit.xml?
> 
> made it work

Fair.

**Comment by calum-gray** [comment]
> > > Why did you remove the requireCoverageMetadata?
> > > Can you explain the change made to line 41 in phpunit.xml?
> > 
> > 
> > made it work
> 
> Fair.

https://dkarlovi.github.io/lying-coverage/

**Review by AnthonyEdmonds — APPROVED** [review]

**Pull request merged**
